log_name: "dreambooth"
pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
revision: null
tokenizer_name: null
instance_data_dir: null
class_data_dir: null
class_prompt: null
with_prior_preservation: false
prior_loss_weight: 1.0
num_class_images: 100
seed: null
resolution: 512
center_crop: false
train_text_encoder: true
train_batch_size: 1
sample_batch_size: 4
num_train_epochs: 1
phase1_train_steps: 500
phase2_train_steps: 500
checkpointing_steps: 5000
resume_from_checkpoint: null
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 2.0e-06
initial_learning_rate: 0.0005
scale_lr: false
lr_scheduler: "constant"
lr_warmup_steps: 0
lr_num_cycles: 1
lr_power: 1.0
use_8bit_adam: false
dataloader_num_workers: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
hub_token: null
hub_model_id: null
logging_dir: "logs"
allow_tf32: false
report_to: "tensorboard"
mixed_precision: "fp16"
prior_generation_precision: null
local_rank: -1
enable_xformers_memory_efficient_attention: false
set_grads_to_none: false
lambda_attention: 0.01
img_log_steps: 200
num_of_assets: 3
initializer_tokens: []
placeholder_tokens: "<asset>"
apply_masked_loss: true
log_checkpoints: false
max_train_steps: 1000
